import { integer, pgTable, text, timestamp, boolean, serial, index } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), language: text('language').notNull().default('en'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expires_at').notNull(), createdAt: timestamp('created_at').defaultNow(), updatedAt: timestamp('updated_at').defaultNow() })
export const categories = pgTable('categories', { id: serial('id').primaryKey(), name: text('name').notNull().unique(), createdAt: timestamp('created_at').notNull().defaultNow() })
export const donations = pgTable('donations', { id: serial('id').primaryKey(), title: text('title').notNull(), category: text('category').notNull(), provider: text('provider').notNull(), quantity: text('quantity').notNull(), expiryAt: timestamp('expiry_at').notNull(), description: text('description').notNull(), price: text('price').notNull().default('Free'), deliveryAvailable: boolean('delivery_available').notNull().default(false), status: text('status').notNull().default('active'), createdAt: timestamp('created_at').notNull().defaultNow(), posterUserId: text('poster_user_id'), posterEmail: text('poster_email'), posterPhone: text('poster_phone'), posterContactKey: text('poster_contact_key'), imageUrl: text('image_url') }, table => ({ contactIdx: index('donations_poster_contact_idx').on(table.posterContactKey) }))
export const claims = pgTable('claims', { id: serial('id').primaryKey(), donationId: integer('donation_id').notNull(), claimantEmail: text('claimant_email'), claimantPhone: text('claimant_phone'), claimantContactKey: text('claimant_contact_key').notNull(), status: text('status').notNull().default('claimed'), createdAt: timestamp('created_at').notNull().defaultNow() }, table => ({ claimantIdx: index('claims_contact_idx').on(table.claimantContactKey), donationIdx: index('claims_donation_idx').on(table.donationId) }))
export const pointEvents = pgTable('point_events', { id: serial('id').primaryKey(), contactKey: text('contact_key').notNull(), points: integer('points').notNull(), reason: text('reason').notNull(), createdAt: timestamp('created_at').notNull().defaultNow() })
export const feedback = pgTable('feedback', { id: serial('id').primaryKey(), donationId: integer('donation_id').notNull(), posterUserId: text('poster_user_id').notNull(), receiverUserId: text('receiver_user_id').notNull(), rating: integer('rating').notNull(), comment: text('comment'), isPublic: boolean('is_public').notNull().default(true), createdAt: timestamp('created_at').notNull().defaultNow() })
export const betterAuthUser = user
export const betterAuthSession = session
export const betterAuthAccount = account
export const betterAuthVerification = verification
