import { integer, pgTable, text, timestamp, boolean, serial } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expires_at').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow(), ipAddress: text('ip_address'), userAgent: text('user_agent'), userId: text('user_id').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('account_id').notNull(), providerId: text('provider_id').notNull(), userId: text('user_id').notNull(), accessToken: text('access_token'), refreshToken: text('refresh_token'), idToken: text('id_token'), accessTokenExpiresAt: timestamp('access_token_expires_at'), refreshTokenExpiresAt: timestamp('refresh_token_expires_at'), scope: text('scope'), password: text('password'), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expires_at').notNull(), createdAt: timestamp('created_at').defaultNow(), updatedAt: timestamp('updated_at').defaultNow() })
export const categories = pgTable('categories', { id: serial('id').primaryKey(), name: text('name').notNull().unique(), createdAt: timestamp('created_at').notNull().defaultNow() })
export const donations = pgTable('donations', { id: serial('id').primaryKey(), title: text('title').notNull(), category: text('category').notNull(), provider: text('provider').notNull(), quantity: text('quantity').notNull(), expiryAt: timestamp('expiry_at').notNull(), description: text('description').notNull(), price: text('price').notNull().default('Free'), deliveryAvailable: boolean('delivery_available').notNull().default(false), status: text('status').notNull().default('active'), createdAt: timestamp('created_at').notNull().defaultNow(), posterUserId: text('poster_user_id') })
export const feedback = pgTable('feedback', { id: serial('id').primaryKey(), donationId: integer('donation_id').notNull(), posterUserId: text('poster_user_id').notNull(), receiverUserId: text('receiver_user_id').notNull(), rating: integer('rating').notNull(), comment: text('comment'), isPublic: boolean('is_public').notNull().default(true), createdAt: timestamp('created_at').notNull().defaultNow() })
export const betterAuthUser = user
export const betterAuthSession = session
export const betterAuthAccount = account
export const betterAuthVerification = verification
