import { integer, pgTable, text, timestamp, boolean, serial } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').defaultNow(), updatedAt: timestamp('updatedAt').defaultNow() })
export const categories = pgTable('categories', { id: serial('id').primaryKey(), name: text('name').notNull().unique(), createdAt: timestamp('created_at').notNull().defaultNow() })
export const donations = pgTable('donations', { id: serial('id').primaryKey(), title: text('title').notNull(), category: text('category').notNull(), provider: text('provider').notNull(), quantity: text('quantity').notNull(), expiryAt: timestamp('expiry_at').notNull(), description: text('description').notNull(), price: text('price').notNull().default('Free'), deliveryAvailable: boolean('delivery_available').notNull().default(false), status: text('status').notNull().default('active'), createdAt: timestamp('created_at').notNull().defaultNow(), posterUserId: text('poster_user_id') })
export const feedback = pgTable('feedback', { id: serial('id').primaryKey(), donationId: integer('donation_id').notNull(), posterUserId: text('poster_user_id').notNull(), receiverUserId: text('receiver_user_id').notNull(), rating: integer('rating').notNull(), comment: text('comment'), isPublic: boolean('is_public').notNull().default(true), createdAt: timestamp('created_at').notNull().defaultNow() })
