'use client'

import { FormEvent, useEffect, useState } from 'react'
import { ArrowRight, Check, Leaf } from 'lucide-react'
import { SiteHeader } from '@/components/site-header'
import { BackHome } from '@/components/back-home'
import { useCopy } from '@/components/locale-provider'

const defaults = ['Fresh produce', 'Pantry staples', 'Prepared meals', 'Bakery & bread']
export default function PostPage() {
  const t = useCopy(); const [sent,setSent]=useState(false); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const [categories,setCategories]=useState(defaults)
  useEffect(()=>{ fetch('/api/categories').then(r=>r.json()).then(data=>Array.isArray(data)&&setCategories([...new Set([...defaults,...data])])).catch(()=>{}) },[])
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError('');const form=event.currentTarget;const formData=new FormData(form); const rawExpiry = String(formData.get('expiryAt') || ''); const payload={...Object.fromEntries(formData.entries()), deliveryAvailable:formData.get('deliveryAvailable') === 'true', expiryAt: rawExpiry ? new Date(rawExpiry).toISOString() : ''};try{const response=await fetch('/api/posts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to publish this item.');setSent(true);form.reset()}catch(error){setError(error instanceof Error?error.message:'Unable to publish this item.')}finally{setLoading(false)}}
  return <main><SiteHeader/><section className="inner-hero post-hero"><BackHome/><div className="inner-kicker">{t.shareKicker}</div><h1>{t.postTitle}</h1><p>{t.postIntro}</p></section><section className="post-form-section"><div className="post-form-intro"><Leaf size={28}/><h2>{t.formHeading}.</h2><p>{t.contactHint}</p></div>{sent?<div className="success-panel" role="status"><span><Check size={25}/></span><h2>Your item is ready to share.</h2><p>Use {t.myPosts} to track it with the same contact details.</p><button className="sample-button" onClick={()=>setSent(false)}>Post another item <ArrowRight size={17}/></button></div>:<form className="share-form" onSubmit={submit}><label>{t.foodName}<input name="title" required placeholder="Fresh garden vegetables"/></label><div className="form-row"><label>{t.category}<select name="category" defaultValue="" required><option value="" disabled>Select a category</option>{categories.map(category=><option key={category}>{category}</option>)}</select></label><label>{t.quantity}<input name="quantity" required placeholder="3 boxes"/></label></div><label>{t.provider}<input name="provider" required placeholder="Restaurant, neighbor, or landmark"/></label><label>{t.expiry}<input name="expiryAt" type="datetime-local" required/></label><label>{t.description}<textarea name="description" required rows={4} placeholder="Tell neighbors what they should know"/></label><label>Image URL (optional)<input name="imageUrl" type="url" placeholder="https://..." /></label><div className="form-row"><label>{t.emailOptional}<input name="email" type="email" placeholder="you@example.com"/></label><label>{t.phoneOptional}<input name="phone" type="tel" placeholder="+1 555 000 0000"/></label></div><label>{t.delivery}<select name="deliveryAvailable" defaultValue="false"><option value="false">{t.discussDelivery}</option><option value="true">{t.deliveryAvailable}</option></select></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button button-dark" disabled={loading}>{loading?'Publishing…':t.postItem}<ArrowRight size={17}/></button></form>}</section></main>
}
