'use client'

import { FormEvent, useEffect, useState } from 'react'
import { ArrowRight, Check, Leaf, Plus } from 'lucide-react'
import { SiteHeader } from '@/components/site-header'
import { BackHome } from '@/components/back-home'

const defaults = ['Fresh produce', 'Pantry staples', 'Prepared meals', 'Bakery & bread']
export default function PostPage() {
  const [sent, setSent] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [categories, setCategories] = useState(defaults); const [newCategory, setNewCategory] = useState(''); const [addingCategory, setAddingCategory] = useState(false)
  useEffect(() => { fetch('/api/categories').then(r => r.json()).then(data => Array.isArray(data) && setCategories(data)).catch(() => {}) }, [])
  async function createCategory() { setAddingCategory(true); setError(''); const response = await fetch('/api/categories', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ name:newCategory }) }); const result = await response.json(); if (!response.ok) setError(result.error || 'Unable to create category.'); else { setCategories(current => [...new Set([...current, result.name])]); setNewCategory('') }; setAddingCategory(false) }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(''); const form = new FormData(event.currentTarget); try { const response = await fetch('/api/posts', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(Object.fromEntries(form.entries())) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to publish this item.'); setSent(true); event.currentTarget.reset() } catch (submitError) { setError(submitError instanceof Error ? submitError.message : 'Unable to publish this item right now.') } finally { setLoading(false) } }
  return <main><SiteHeader /><section className="inner-hero post-hero"><BackHome /><div className="inner-kicker">SHARE THE EXTRA</div><h1>Put it on<br /><em>the table.</em></h1><p>One post can make someone&apos;s day — and keep perfectly good food out of the bin.</p></section><section className="post-form-section"><div className="post-form-intro"><Leaf size={28} /><h2>Tell us what you have.</h2><p>No account needed. Add an email or phone so neighbors can reach you about this post.</p></div>{sent ? <div className="success-panel" role="status"><span><Check size={25} /></span><h2>Your item is ready to share.</h2><p>Use My posts in the header to track it using the same contact details.</p><button className="sample-button" onClick={() => setSent(false)}>Post another item <ArrowRight size={17} /></button></div> : <form className="share-form" onSubmit={submit}><label>Food name<input name="title" required placeholder="e.g. Fresh garden vegetables" /></label><div className="form-row"><label>Category<select name="category" defaultValue="" required><option value="" disabled>Select a category</option>{categories.map(category => <option key={category}>{category}</option>)}</select></label><label>Quantity<input name="quantity" required placeholder="e.g. 3 boxes" /></label></div><div className="new-category-row"><input value={newCategory} onChange={event => setNewCategory(event.target.value)} placeholder="Create a new category" /><button type="button" className="category-add" onClick={createCategory} disabled={addingCategory || !newCategory.trim()}><Plus size={15} /> Add category</button></div><label>Provider or pickup location<input name="provider" required placeholder="Company, restaurant, individual, or landmark" /></label><label>Best before<input name="expiryAt" type="datetime-local" required /></label><label>Delivery available<select name="deliveryAvailable" defaultValue="false"><option value="false">Pickup only</option><option value="true">Yes, delivery available</option></select></label><label>Description<textarea name="description" required rows={5} placeholder="What should neighbors know?" /></label><fieldset><legend>How can neighbors contact you? <span aria-hidden="true">*</span></legend><div className="form-row"><label>Email<input name="email" type="email" placeholder="you@example.com" /></label><label>Phone<input name="phone" type="tel" placeholder="+1 555 000 0000" /></label></div><small>One contact method is required. We only show your details to people involved in this post.</small></fieldset>{error && <p className="form-error" role="alert">{error}</p>}<button className="button button-dark form-submit" disabled={loading}>{loading ? 'Publishing…' : 'Publish item'} <ArrowRight size={18} /></button></form>}</section></main>
}
