import { NextResponse } from 'next/server'
import { desc, eq, or } from 'drizzle-orm'
import { db } from '@/lib/db'
import { donations } from '@/lib/db/schema'
import { ensureAnonymousSchema, normalizeContact, validContact } from '@/lib/contact'

export async function GET() { try { await ensureAnonymousSchema(); const rows = await db.select().from(donations).where(eq(donations.status, 'active')).orderBy(desc(donations.createdAt)); return NextResponse.json(rows) } catch { return NextResponse.json({ error: 'Unable to load posts' }, { status: 500 }) } }

export async function POST(request: Request) {
  try { await ensureAnonymousSchema(); const body = await request.json() as Record<string, unknown>; const title = typeof body.title === 'string' ? body.title.trim() : ''; const category = typeof body.category === 'string' ? body.category.trim() : ''; const quantity = typeof body.quantity === 'string' ? body.quantity.trim() : ''; const provider = typeof body.provider === 'string' ? body.provider.trim() : ''; const description = typeof body.description === 'string' ? body.description.trim() : ''; const expiryAt = typeof body.expiryAt === 'string' ? new Date(body.expiryAt) : null; const contact = normalizeContact(body.email, body.phone); if (!title || !category || !quantity || !provider || !description || !expiryAt || Number.isNaN(expiryAt.getTime())) return NextResponse.json({ error: 'Please complete every field with valid information.' }, { status: 400 }); if (expiryAt.getTime() <= Date.now()) return NextResponse.json({ error: 'Best before must be in the future.' }, { status: 400 }); if (!validContact(contact)) return NextResponse.json({ error: 'Add an email or phone number so neighbors can contact you.' }, { status: 400 }); const [post] = await db.insert(donations).values({ title, category, quantity, provider, description, expiryAt, posterEmail: contact.email, posterPhone: contact.phone, posterContactKey: contact.key, price: 'Free', deliveryAvailable: body.deliveryAvailable === 'true', status: 'active' }).returning(); return NextResponse.json({ post }, { status: 201 }) } catch (error) { console.error('[v0] anonymous post creation failed', error); return NextResponse.json({ error: 'We could not publish that item. Please try again.' }, { status: 500 }) }
}
