import { NextResponse } from 'next/server'
import { desc, eq, or } from 'drizzle-orm'
import { db } from '@/lib/db'
import { donations } from '@/lib/db/schema'
import { ensureAnonymousSchema, normalizeContact, validContact } from '@/lib/contact'

const sampleItems = [
  ...['Fresh produce','Pantry staples','Prepared meals','Bakery & bread'].flatMap((category, index) => [
    { id: -(index * 3 + 1), title: ['Garden vegetables','Rice and lentil pantry box','Family pasta dinner','Morning bakery basket'][index], category, provider: ['Greenway neighbors','Community pantry','Riverside kitchen','Sunrise bakery'][index], quantity: ['3 boxes','8 portions','5 meals','2 bags'][index], expiryAt: new Date(Date.now()+86400000*(index+1)).toISOString(), description: ['Seasonal vegetables, washed and ready to cook.','Rice, lentils, beans, and spices for a generous meal.','Freshly prepared vegetarian pasta with salad.','Bread, rolls, and pastries from today’s bake.'][index], deliveryAvailable: index === 2, status:'active' },
    { id: -(index * 3 + 2), title: ['Fruit share bag','Canned goods bundle','Soup for neighbors','Sourdough loaves'][index], category, provider: ['Maple street','Good Neighbors Hub','Oak community kitchen','Corner oven'][index], quantity: ['4 bags','12 cans','6 containers','4 loaves'][index], expiryAt: new Date(Date.now()+86400000*(index+2)).toISOString(), description: ['Apples, bananas, and oranges to share.','A shelf-stable mix for your pantry.','Warm vegetable soup, portioned and labeled.','Fresh loaves baked this morning.'][index], deliveryAvailable: false, status:'active' },
    { id: -(index * 3 + 3), title: ['Herb and greens box','Breakfast staples','Rice bowl portions','Pastry assortment'][index], category, provider: ['Willow allotment','Eastside pantry','Local meal team','Baker’s table'][index], quantity: ['2 boxes','1 crate','8 bowls','3 boxes'][index], expiryAt: new Date(Date.now()+86400000*(index+3)).toISOString(), description: ['Leafy greens and herbs from a local garden.','Oats, cereal, and breakfast basics.','Balanced rice bowls ready for pickup.','Sweet and savory pastries to share.'][index], deliveryAvailable: index === 0, status:'active' },
  ])
]
export async function GET() { try { await ensureAnonymousSchema(); const rows = await db.select().from(donations).where(eq(donations.status, 'active')).orderBy(desc(donations.createdAt)); return NextResponse.json(rows.length ? rows : sampleItems) } catch { return NextResponse.json(sampleItems) } }

export async function POST(request: Request) {
  try { await ensureAnonymousSchema(); const body = await request.json() as Record<string, unknown>; const title = typeof body.title === 'string' ? body.title.trim() : ''; const category = typeof body.category === 'string' ? body.category.trim() : ''; const quantity = typeof body.quantity === 'string' ? body.quantity.trim() : ''; const provider = typeof body.provider === 'string' ? body.provider.trim() : ''; const description = typeof body.description === 'string' ? body.description.trim() : ''; const expiryAt = typeof body.expiryAt === 'string' || typeof body.expiryAt === 'number' ? new Date(body.expiryAt) : null; const contact = normalizeContact(body.email, body.phone); if (!title || !category || !quantity || !provider || !description || !expiryAt || Number.isNaN(expiryAt.getTime())) return NextResponse.json({ error: 'Please complete every field with valid information.' }, { status: 400 }); if (expiryAt.getTime() <= Date.now()) return NextResponse.json({ error: 'Best before must be in the future.' }, { status: 400 }); if (!validContact(contact)) return NextResponse.json({ error: 'Add an email or phone number so neighbors can contact you.' }, { status: 400 }); const [post] = await db.insert(donations).values({ title, category, quantity, provider, description, expiryAt, posterEmail: contact.email, posterPhone: contact.phone, posterContactKey: contact.key, price: 'Free', deliveryAvailable: body.deliveryAvailable === true || body.deliveryAvailable === 'true', status: 'active' }).returning(); return NextResponse.json({ post }, { status: 201 }) } catch (error) { console.error('[v0] anonymous post creation failed', error); return NextResponse.json({ error: 'We could not publish that item. Please try again.' }, { status: 500 }) }
}
