import Link from 'next/link'
import { ArrowRight, Check, Heart, Leaf, PackageOpen, Users } from 'lucide-react'
import { SiteHeader } from '@/components/site-header'
import { BackHome } from '@/components/back-home'

const steps = [
  ['01', 'Share what you have', 'Post surplus groceries, prepared food, pantry items, or fresh produce in under a minute.'],
  ['02', 'Find what you need', 'Browse nearby donations by category, quantity, and availability.'],
  ['03', 'Arrange a handoff', 'Connect respectfully, choose a pickup time, and keep good food moving locally.'],
]

export default function AboutPage() {
  return <main><SiteHeader /><section className="inner-hero about-hero"><BackHome /><div className="inner-kicker">OUR PURPOSE</div><h1>Good food is<br /><em>worth sharing.</em></h1><p>sharetable is a community food exchange helping neighbors, kitchens, and local organizations turn surplus into support.</p></section><section className="about-problem"><div><span className="section-label">THE PROBLEM</span><h2>Waste is a<br /><em>shared problem.</em></h2></div><div className="about-body"><p>Food is wasted at every step of the journey: at the market, in commercial kitchens, in homes, and on the shelves of community organizations. Meanwhile, many people are stretching meals, choosing between essentials, or simply looking for affordable fresh food.</p><p>sharetable closes that local gap. Instead of throwing away useful food, people can donate it to someone nearby. A spare loaf, a box of produce, or a prepared meal can become a meaningful act of care.</p></div></section><section className="benefit-band"><div><span className="section-label">WHY DONATE</span><h2>One extra item<br />can make a <em>difference.</em></h2></div><div className="benefit-list"><p><Check /> Reduce household and business food waste.</p><p><Check /> Help neighbors access nutritious food.</p><p><Check /> Strengthen trust and connection locally.</p><p><Check /> Keep resources in use instead of landfills.</p></div></section><section className="about-steps"><div className="steps-heading"><span className="section-label">HOW IT WORKS</span><h2>Sharing made<br /><em>simple.</em></h2><p>Whether you are donating or receiving, the whole exchange is designed to feel clear, safe, and human.</p></div><div className="steps-list">{steps.map(([number, title, copy]) => <div className="step-row" key={number}><span className="step-number">{number}</span><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div></section><section className="values-section"><div className="value-card"><Leaf /><h3>Local first</h3><p>Every exchange starts with the people and places closest to you, so food travels less and helps more.</p></div><div className="value-card"><Heart /><h3>Dignity always</h3><p>Donating and receiving should feel welcoming, respectful, and free of judgment.</p></div><div className="value-card"><Users /><h3>Better together</h3><p>Small acts become lasting change when an entire community joins in.</p></div></section><section className="about-cta"><PackageOpen size={32} /><h2>Have something useful to share?</h2><p>Give surplus a second life today.</p><Link className="sample-button" href="/post">Post a donation <ArrowRight size={17} /></Link></section></main>
}
