'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, CalendarDays, MapPin, Search, Truck, UserRound } from 'lucide-react'
import { SiteHeader } from '@/components/site-header'
import { BackHome } from '@/components/back-home'
import { useCopy } from '@/components/locale-provider'

type Item = { id:number; title:string; provider:string; category:string; expiryAt:string; quantity:string; description:string; deliveryAvailable:boolean; status:string; imageUrl?:string|null }
const types = ['All items', 'Fresh produce', 'Pantry staples', 'Prepared meals', 'Bakery & bread']
export default function BrowsePage() { const t = useCopy(); const [items,setItems]=useState<Item[]>([]); const [query,setQuery]=useState(''); const [type,setType]=useState('All items'); const [selected,setSelected]=useState<Item|null>(null); const [email,setEmail]=useState(''); const [phone,setPhone]=useState(''); const [message,setMessage]=useState('');
  useEffect(()=>{fetch('/api/posts').then(r=>r.json()).then(data=>setItems(Array.isArray(data)?data:(Array.isArray(data.items)?data.items:[]))).catch(()=>{})},[])
  const filtered=useMemo(()=>items.filter(item=>(type==='All items'||item.category===type)&&`${item.title} ${item.provider} ${item.description}`.toLowerCase().includes(query.toLowerCase())),[items,query,type])
  async function claim(){ if(!selected)return; const response=await fetch('/api/claims',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({donationId:selected.id,email,phone})}); const result=await response.json(); setMessage(response.ok?'Claimed. The poster can now coordinate with you.':result.error); if(response.ok){setItems(current=>current.filter(item=>item.id!==selected.id));setSelected(null)} }
  return <main><SiteHeader /><section className="inner-hero browse-hero"><BackHome /><div className="inner-kicker">FRESH FROM THE COMMUNITY</div><h1>{t.browseTitle}</h1><p>{t.browseIntro}</p></section><section className="browse-page-content"><div className="browse-toolbar"><div className="browse-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search} aria-label={t.search}/></div><div className="browse-filters">{types.map(item=><button className={type===item?'selected':''} onClick={()=>setType(item)} key={item}>{item}</button>)}</div></div><div className="browse-results"><span>{filtered.length} available items</span><span>Sorted by expiry date</span></div><div className="browse-card-grid">{filtered.map(item=><article className="food-card" key={item.id}><div className="food-card-art green">{item.imageUrl ? <img src={item.imageUrl} alt="" /> : <span>{item.category.charAt(0)}</span>}</div><div className="food-card-body"><span className="item-type">{item.category}</span><h2>{item.title}</h2><p className="food-description">{item.description}</p><div className="food-provider"><span><UserRound size={14}/> {item.provider}</span><span><MapPin size={14}/> {t.pickup}</span></div><div className="food-meta"><span><CalendarDays size={14}/> Expires {new Date(item.expiryAt).toLocaleString()}</span><span><Truck size={14}/> {item.deliveryAvailable?t.deliveryAvailable:t.discussDelivery}</span></div><button className="claim-outline" onClick={()=>{setSelected(item);setMessage('')}}>{t.claim} <ArrowRight size={16}/></button></div></article>)}</div>{message && <p className="form-error" role="status">{message}</p>}</section>{selected && <div className="modal-backdrop" role="presentation" onClick={()=>setSelected(null)}><div className="lookup-card claim-modal" role="dialog" aria-modal="true" aria-labelledby="claim-title" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Close">×</button><span className="section-kicker">{t.claim} {selected.title}</span><h2 id="claim-title">How can the poster reach you?</h2><p>No account needed. One contact method is required.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Phone<input type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+1 555 000 0000"/></label><button className="button button-dark" onClick={claim}>Confirm claim <ArrowRight size={17}/></button></div></div>}</main>
}
