'use client'
import { useMemo, useState } from 'react'
import { ArrowRight, CalendarDays, MapPin, Search, Truck, UserRound } from 'lucide-react'
import { SiteHeader } from '@/components/site-header'
import { BackHome } from '@/components/back-home'
const types = ['All items', 'Fresh produce', 'Pantry staples', 'Prepared meals', 'Bakery & bread']
const groups = [['Fresh market produce box','Harvest Co-op','Fresh produce','Today, 6:00 PM','8 boxes','green','Fresh seasonal fruits and vegetables, packed this morning.'],['Garden greens bundle','Leah’s community garden','Fresh produce','Today, 7:30 PM','10 bundles','green','Leafy greens, herbs, and salad leaves from a neighborhood garden.'],['Orchard fruit basket','Greenway Market','Fresh produce','Tomorrow, 9:00 AM','12 baskets','green','Apples, pears, and oranges with a few ripe bananas.'],['Pantry staples bundle','Good Neighbor Org','Pantry staples','Today, 5:00 PM','12 bundles','yellow','Rice, lentils, beans, pasta, and shelf-stable pantry essentials.'],['Rice and lentil share','Mariam’s pantry','Pantry staples','Tomorrow, 10:00 AM','13 packs','yellow','A nourishing pantry pack for a household or community kitchen.'],['Vegetable curry portions','Saffron House','Prepared meals','Today, 8:00 PM','10 portions','blue','Warm vegetable curry prepared today and ready for pickup.'],['Tomato pasta supper','Corner Kitchen','Prepared meals','Today, 7:00 PM','11 portions','blue','Vegetarian pasta made with a tomato and basil sauce.'],['Sourdough loaves','Mina’s Bakery','Bakery & bread','Tomorrow, 9:00 AM','12 loaves','peach','Hand-shaped sourdough loaves baked yesterday and still delicious.'],['Morning buns','Dawn Bakehouse','Bakery & bread','Tomorrow, 10:30 AM','13 pieces','peach','Cinnamon morning buns, individually wrapped for easy pickup.']]
const items = groups.map(([title, provider, type, expiry, quantity, color, description]) => ({ title, provider, type, expiry, quantity, color, description, delivery: provider.includes('Org') || provider.includes('Kitchen') }))
export default function BrowsePage() { const [query,setQuery]=useState(''); const [type,setType]=useState('All items'); const filtered=useMemo(()=>items.filter(item=>(type==='All items'||item.type===type)&&`${item.title} ${item.provider} ${item.description}`.toLowerCase().includes(query.toLowerCase())),[query,type]); return <main><SiteHeader /><section className="inner-hero browse-hero"><BackHome /><div className="inner-kicker">FRESH FROM THE COMMUNITY</div><h1>Find something<br /><em>good nearby.</em></h1><p>Browse food shared by neighbors, local kitchens, and organizations in your community.</p></section><section className="browse-page-content"><div className="browse-toolbar"><div className="browse-search"><Search size={18} /><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search meals, bakeries, neighbors..." aria-label="Search items" /></div><div className="browse-filters">{types.map(item=><button className={type===item?'selected':''} onClick={()=>setType(item)} key={item}>{item}</button>)}</div></div><div className="browse-results"><span>{filtered.length} available items</span><span>Sorted by expiry date</span></div><div className="browse-card-grid">{filtered.map((item,index)=><article className="food-card" key={`${item.title}-${index}`}><div className={`food-card-art ${item.color}`}><span>{item.type === 'Bakery & bread' ? 'B' : item.type === 'Fresh produce' ? 'F' : item.type === 'Prepared meals' ? 'P' : 'S'}</span></div><div className="food-card-body"><span className="item-type">{item.type}</span><h2>{item.title}</h2><p className="food-description">{item.description}</p><div className="food-provider"><span><UserRound size={14} /> {item.provider}</span><span><MapPin size={14} /> Community pickup</span></div><div className="food-meta"><span><CalendarDays size={14} /> Expires {item.expiry}</span><span><Truck size={14} /> {item.delivery ? 'Delivery available' : 'Pickup only'}</span></div><button className="claim-outline">View item <ArrowRight size={15} /></button></div></article>)}</div>{filtered.length===0&&<div className="browse-empty"><h2>No items found</h2><p>Try another search or browse all categories.</p><button className="sample-button" onClick={()=>{setQuery('');setType('All items')}}>Show all items</button></div>}</section></main> }
