import Link from 'next/link'
import { ArrowRight, Check, Leaf, Sparkles } from 'lucide-react'
import { SiteHeader } from '@/components/site-header'

const shelfImage = '/images/food-shelf.png'

export default function HomePage() {
  return <main><SiteHeader /><section className="editorial-hero"><div className="editorial-copy"><p className="editorial-eyebrow"><Sparkles size={17} /> A LITTLE GOES A LONG WAY</p><h1>Redistribute<br />surplus.<br /><em>Reduce waste.</em></h1><p className="editorial-lede">Exchange food, fresh produce, and pantry staples with people in your community. What you have extra could be exactly what someone else needs.</p><div className="editorial-actions"><Link href="/browse" className="sample-button">Browse available items <ArrowRight size={18} /></Link><Link href="/post" className="sample-quiet-link">Share something <ArrowRight size={16} /></Link></div></div><div className="editorial-visual"><div className="sample-stat"><span><Check size={19} /></span><div><strong>12 items</strong><small>exchanged today</small></div></div><img src={shelfImage} alt="Fresh fruits, vegetables, bread, and pantry staples arranged on a wooden shelf" /><span className="sample-caption"><Leaf size={16} /> Fresh finds nearby</span></div></section><section className="sample-impact"><div><strong>2,480</strong><span>items shared</span></div><div><strong>640</strong><span>neighbors connected</span></div><div><strong>18</strong><span>local partners</span></div><p>Small exchanges add up<br /><b>to a healthier community.</b></p></section><section className="sample-bottom"><div><p className="editorial-eyebrow">WHAT YOU CAN SHARE</p><h2>There is always<br /><em>enough to go around.</em></h2></div><div className="share-types"><span>Fresh produce</span><span>Pantry staples</span><span>Prepared meals</span><span>Bakery & bread</span></div></section></main>
}
